

server:
  port: 8888
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          basedir: ${HOME}/IdeaProjects/bbmicroservices/config-files

#          basedir: config-files

