version: '2.1'
services:
  config:
    build: config
    ports:
      - 8888:8888

  registry:
    build: registry

  gateway:
    build: gateway

  auth-service:
    build: auth-service
    ports:
      - 5000:5000

  auth-mongodb:
    build: mongodb
    ports:
      - 25000:27017

  message:
    build: message
    ports:
      - 7000:7000


  message-mongodb:
    build: mongodb
    ports:
      - 26000:27017

