version: '2.1'
services:
  config:
    image: brookzhang/bbmicroservice-config
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  registry:
    image: brookzhang/bbmicroservice-registry
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 7003:7003
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway:
    image: brookzhang/bbmicroservice-gateway
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 7002:7002
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-service:
    environment:
      CONFIG_SERVICE_PASSWORD: 12345
      NOTIFICATION_SERVICE_PASSWORD: 12345
      STATISTICS_SERVICE_PASSWORD: 12345
      ACCOUNT_SERVICE_PASSWORD: 12345
      MONGODB_PASSWORD: 12345
    image: brookzhang/bbmicroservices-auth-service
    restart: always
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-mongodb:
    environment:
      MONGODB_PASSWORD: 12345
    image: brookzhang/bbmicroservices-mongodb
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  message-service:
    image: brookzhang/bbmicroservices-message-service
    environment:
      MONGODB_PASSWORD: 12345
    restart: always
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  message-mongodb:
    image: brookzhang/bbmicroservices-mongodb
    environment:
      INIT_DUMP: message-service-dump.js
      MONGODB_PASSWORD: 12345
    restart: always

    logging:
      options:
        max-size: "10m"
        max-file: "10"

