version: '2.1'
services:
  config:
    build: config
    ports:
      - 8888:8888

  registry:
    build: registry

  gateway:
    build: gateway

#  auth-server:
#    build: auth-server
#    ports:
#      - 5000:5000

#  auth-mongodb:
#    build: mongodb
#    ports:
#      - 25000:27017

#  message:
#    build: message


#  message-mongodb:
#    build: mongodb

