version: '2.1'
services:
  config:
    build: config
    ports:
      - 7001:7001

  registry:
    build: registry

  gateway:
    build: gateway

  auth-service:
    build: auth-service
    ports:
      - 7004:7004

  auth-mongodb:
    build: mongodb
    ports:
      - 25000:27017

  message-service:
    build: message-service
    ports:
      - 7005:7005


  message-mongodb:
    build: mongodb
    ports:
      - 26000:27017

