server:
  port: 7002

spring:
  data:
    mongodb:
      host: 127.0.0.1
      database: microservices
      port: 27017
  application:
    name: auth-server

#security:
#  oauth2:
#    client:
#      client-id: acme
#      client-secret: acmesecret
#      scope: read,write
#      auto-approve-scopes: '.*'

logging:
  level:
    org.springframework.security: DEBUG