###
GET http://localhost:7000/messages/5b4dc45b7584f2b9192d935b
Authorization: Bearer c256eb81-8f06-4e3e-a6c3-bdad17f44542

###
GET http://localhost:7000/messages
Authorization: Bearer af463f31-3efd-4c0f-9833-9c9a040ee2e2

###
POST http://localhost:7000/messages
Content-Type: application/json
Authorization: Bearer af463f31-3efd-4c0f-9833-9c9a040ee2e2

{
  "receivers": ["13913005642"],
  "content": "just a content 6",
  "sender": "bb"
}

### send message
POST http://localhost:7000/messages/5b63c9dd7ed5573de8b44709
Authorization: Bearer af463f31-3efd-4c0f-9833-9c9a040ee2e2

### delete message
DELETE http://localhost:7000/messages/5b4db8b97584f2b9192d935a

###
POST message-service:12345@localhost:5000/uaa/oauth/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&scope=server

###
