###
GET http://localhost:7000/messages/5b4dc45b7584f2b9192d935b

###
GET http://localhost:7000/messages
Authorization: Bearer fab62977-807c-4313-a123-290eee0e27cb

###
POST http://localhost:7000/messages
Content-Type: application/json

{
  "receivers": ["133000000","13913005642"],
  "content": "just a content 5",
  "sender": "bb"
}

### send message
POST http://localhost:7000/messages/5b4dc45b7584f2b9192d935b

### delete message
DELETE http://localhost:7000/messages/5b4db8b97584f2b9192d935a

###