server:
  port: 7001

spring:
  data:
    mongodb:
      host: message-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: bbmicroservices
      port: 27017
  application:
    name: message


