
server:
  port: 7000

spring:
  data:
    mongodb:
      host: 127.0.0.1
  #      username: user
  #      password: ${MONGODB_PASSWORD}
      database: microservices
      port: 27017
  application:
    name: message



security:
  oauth2:
    client:
      clientId: acme
      clientSecret: acmesecret
      accessTokenUri: http://localhost:7000/oauth/token
      grantType: client_credentials
      scope: read

    resource:
      userInfoUri: http://localhost:7000/users/current
      token-info-uri: http://localhost:7000/oauth/check_token



