logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://registry:7003/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://auth-service:7004/uaa/users/current

spring:
  rabbitmq:
    host: rabbitmq