spring:
  data:
    mongodb:
#      host: auth-mongodb
#      username: user
#      password: ${MONGODB_PASSWORD}
      host: 127.0.0.1
      uri: mongodb://localhost:27017
      database: bbmicroservices
      port: 27017

server:
#  servlet:
#    context-path: /uaa
  port: 5000

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
