spring:
  data:
    mongodb:
      host: auth-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: bbmicroservices
      port: 27017

server:
  servlet:
    context-path: /uaa
  port: 5000

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://registry:8761/eureka/
  instance:
    hostname: localhost
