spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: bbmicroservices

server:
  servlet:
    context-path: /uaa
  port: 5000

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
