hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    auth-service:
        path: /uaa/**
        url: http://auth-service:7004
        stripPrefix: false
        sensitiveHeaders:

    message-service:
        path: /messages/**
        serviceId: message-service
        stripPrefix: false
        sensitiveHeaders:
server:
  port: 7002
