server:
  port: 7000

spring:
  data:
    mongodb:
      host: message-mongodb
      database: bbmicroservices
      port: 27017

security:
  oauth2:
    client:
      clientId: message-service
      clientSecret: 12345
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      userInfoUri: http://auth-service:5000/uaa/users/current
      grant-type: client_credentials
      scope: server

dahan:
  ribbon:
    listOfServers: http://127.0.0.1:5000,http://www.dh3t.com
  config:
    sign: "【怡安翰威特】"
    url: http://localhost:4000
    password: cf833687fcf6b0e2f790492a19b53258
    subcode: 41631
    account: dh41631
