server:
  port: 7000

spring:
  data:
    mongodb:
      host: localhost
      database: bbmicroservices
      port: 27017
  application:
    name: message-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

security:
  oauth2:
    client:
      clientId: message-service
      clientSecret: 12345
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      userInfoUri: http://localhost:5000/uaa/users/current
      grant-type: client_credentials
      scope: server
