server:
  port: 7000

spring:
  data:
    mongodb:
      host: message-mongodb
      database: bbmicroservices
      port: 27017

security:
  oauth2:
    client:
      clientId: message-service
      clientSecret: 12345
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      userInfoUri: http://auth-service:5000/uaa/users/current
      grant-type: client_credentials
      scope: server

dahan:
  ribbon:
    listOfServers: http://127.0.0.1:5000,http://www.dh3t.com