###
GET http://localhost:7001/users/current

###
POST http://localhost:7001/users
Content-Type: application/json

{
    "username":"brook",
    "password":"fighting"
}

###
GET http://localhost:7001/users
Authorization: Bear 6066d561-0bbe-47df-bb05-aec8cd679cb1


###
POST acme:acmesecret@localhost:7001/oauth/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&scope=read

###
POST bb:12345@localhost:7001/oauth/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&scope=write
#{
#    "grant_type": "client_credentials",
#    "scope":"server"
#}

###
GET acme:acmesecret@localhost:7001/oauth/token?grant_type=client_credentials

###
POST http://localhost:7001/oauth/check_token
Content-Type: application/x-www-form-urlencoded

token = 8d75ae42-d394-4723-acef-7b36869bba89

###