###
GET http://localhost:7001/users/current

###
POST http://localhost:7001/users
Content-Type: application/json

{
    "username":"brook",
    "password":"fighting"
}

###
GET http://localhost:7001/users
Authorization: Bearer 8855260b-787a-4435-8ad8-69abbe757957


### client_credentials
POST acme:acmesecret@localhost:7001/oauth/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&scope=read

### client_credentials
POST bb:12345@localhost:7001/oauth/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&scope=write


### password
POST ui:12345@localhost:7001/oauth/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=brook&password=fighting

###
GET acme:acmesecret@localhost:7001/oauth/token?grant_type=client_credentials

###
POST http://localhost:7001/oauth/check_token
Content-Type: application/x-www-form-urlencoded

token = 8d75ae42-d394-4723-acef-7b36869bba89

### get current users
GET http://localhost:7001/users/current
Authorization: Bearer 7ceb3826-acd3-48b4-8827-566522e3b68d

###